version: '3.8'

services:
  socks5-proxy:
    image: serjs/go-socks5-proxy
    container_name: socks5-proxy
    restart: always
    ports:
      - "1080:1080"
    environment:
      PROXY_USER: yourUsername
      PROXY_PASSWORD: yourPassword